name: 'docker-build'
inputs:
  image-name:
    required: true
  username:
    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.nimeji.com
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ inputs.image-name }}:latest
