name: 'docker-build'
inputs:
  image-name:
    required: true
  github-token:
    required: true
runs:
  using: "composite"
  steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.registry
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.nimeji.com/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
